### ISSUE TITLE
Openunison Hashicorp Vault integration example

### ISSUE THREAD

**Issue by drengskapr** [OpenUnison/openunison-k8s#100]
Hello there!

I have finished integrating Openunison with Vault a couple of days ago and I want to share my knowledge. Where can I do that?

Here is my manual: https://github.com/drengskapr/manuals/blob/main/openunison-vault-integration.md

I would be happy if it ends up in your documentation!

**Comment by mlbiam** [comment]
@drengskapr this is FANTASTIC.  It's great timing too, because i was just about to work on this integration.  I've got the automation of generating SSO between kubernetes and vault, but hadn't yet gotten to SSO between OpenUnison and Vault.  Would you mind submitting a PR?  That way you get credit for having written it.  To get this integrated into the docs:

1. Fork https://github.com/OpenUnison/openunison.github.io
2. Copy your images to assets/images/apps/vault
3. Create docs/applications/vault.md with your integration guide, change your image tags from `![roles](pictures/openunison_roles.png)` --> ![roles](../../assets/images/apps/vault/openunison_roles.png)
4. Submit PR

Thanks again, this is fantastic!

**Comment by drengskapr** [comment]
@mlbiam, sure I'll do it.

**Comment by mlbiam** [comment]
merged.  thanks again @drengskapr !
