### ISSUE TITLE
Change the default to set use_jetstack: true

### ISSUE THREAD

**Issue by erkules** [OpenUnison/openunison-k8s#35]
I got the issue I couldn't use kubectl exec. (Worked with the Dashboard fine)
`error: unable to upgrade connection`
Marc told setting 
`use_jetstack: true`
should be the way to go. So maybe set this as an default?

**Comment by kastl-ars** [comment]
This seems to be the default now?

- https://github.com/OpenUnison/helm-charts/blob/master/orchestra/values.yaml#L79
- https://github.com/OpenUnison/helm-charts/blob/master/orchestra-login-portal/values.yaml#L65

**Comment by erkules** [comment]
Nice catchup. 
Thx

**Comment by mlbiam** [comment]
Sorry about that.  yes, we stopped using OpenUnison's built in proxy for kubectl because kubectl uses the mostly dead SPDY protocol for `kubectl exec` and related commands.  We took over the abandoned kube-oidc-project from jetstack to continue maintaining it - https://www.tremolosecurity.com/post/updating-kube-oidc-proxy
