### ISSUE TITLE
Multiple authentication providers

### ISSUE THREAD

**Issue by giotab** [OpenUnison/openunison-k8s#48]
Is it possible to configure multiple authentication providers on the Portal?
e.g. the option to choose to login either with SAML2 or with OIDC?

The documentation is a little bit confusing as it says 
> **At least one** option is required

as well as 
> Authentication (**One** of activedirectory, oidc, github, or saml)

**Comment by mlbiam** [comment]
> Is it possible to configure multiple authentication providers on the Portal?

Short answer is "Yes".  We have customers in other use cases using OpenUnison with 20+ different identity providers to choose from at login.

> e.g. the option to choose to login either with SAML2 or with OIDC?

Short answer is "Yes".  You can also have multiple instances of each.  For instance you could have an OIDC to both Okta and AzureAD while also having a SAML connection to ADFS and GitHub connections to multiple teams.

What is your use case?  The Helm chart is very specific to make the deployment easier, but everything is controlled by YAML so its just a matter of getting the right CRDs created for your use case.  Happy to help with that.

The general process is:

1. Define a set of `AuthenticationMechanism` objects (if not already defined)
2. Chain them together using an `AuthenticationChain` object
3. Create an endpoint that requires your new chain
4. Add your endpoint to the `LoginService` chain so OpenUnison knows how to authenticate you

The charts assume a single authentication source because that's the most common use case, but it can be done outside the initial installation chart.  Let me know what your use case is and I'll be happy to walk you through the set.

**Comment by giotab** [comment]
Thanks for the prompt reply @mlbiam .
I think i'll manage to update the yaml file accordingly and will reopen the issue if we face any issues!

Cheers
