### ISSUE TITLE
When Login using Okta, does not receive the correct username and roles

### ISSUE THREAD

**Issue by St4n** [OpenUnison/openunison-k8s#88]
![Capture d’écran 2023-11-09 à 14 10 29](https://github.com/OpenUnison/openunison-k8s/assets/2866240/9fc889cc-9368-4041-990c-f3b2d949d568)
Hello,

When correctly login to OKTA, openunison opens with a cryptic username and no roles (please see screen capture)

Can you tell me where I missed something?

Thanks,
Regards,
Stéphane.

**Comment by mlbiam** [comment]
> openunison opens with a cryptic username

This is the `sub` attribute that we receive from Okta.  It is both immutable and not based on the user's name the way an email may be.  In your values.yaml, you can change `oidc.claims.sub` from `sub` to `email` or `name` to change this then run `helm upgrade orchestra-login-portal tremolo/orchestra-login-portal -n openunison -f /path/to/values.yaml` to update

>  and no roles (please see screen capture)

This usually happens because the Okta groups attribute isn't configured.  Did you follow the steps from https://openunison.github.io/identity%20providers/okta/ for groups?  See the below image from the post.  You need to tell Okta what claim to store groups in (`groups`) and which groups will be allowed.

![image](https://github.com/OpenUnison/openunison-k8s/assets/8249283/421e6b26-49a7-46ee-a451-e9a93a77fba3)

**Comment by St4n** [comment]
Following your advices, I managed to make Okta works with OpenUnison, thanks, for your support !

**Comment by vilnitsky** [comment]
HI @mlbiam  I have faced the same issue. Unfortunately can't make the group working, the Roles data remains empty. 
1) At Okta I have configured groups claim filter. 
2) also In Security->Api -> edit -> scopes I had to add "groups" scope since Okta returns invalid_scope error
![Screenshot from 2024-10-31 04-14-45](https://github.com/user-attachments/assets/5e689656-bf3e-4b69-9f1b-8b0c2d172b3c)

would you be able to help please?

**Comment by mlbiam** [comment]
@vilnitsky the scope configuration doesn't enable groups, did you enable the groups in the oidc token per https://openunison.github.io/identity%20providers/okta/ per the screenshot earlier in this request?

**Comment by vilnitsky** [comment]
@mlbiam yes, it's set in the app like this 

![image](https://github.com/user-attachments/assets/878e9ba9-dc42-45aa-a1f3-ef80c16dfcd4)


also if groups isn't defied in the scope configuration, I get "invalid_scope"  error while authentication, not sure if it's normal, so that kinda worked to define groups in the scope configuration, but the roles remains empty on after login

**Comment by vilnitsky** [comment]
@mlbiam waned to give an update on my issue. found a solution here, it was my case
https://support.okta.com/help/s/article/default-authorization-server-missing-groups-scope?language=en_US

Sharing in case someone needs as well. Got working after adding that claim manually.  Thank you for your time!
